<?php

namespace Fuel\Fieldset\Input;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-17 at 16:38:28.
 */
class CheckboxTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
		$this->object = new Checkbox;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
	
	/**
	 * @covers FuelPHP\Fieldset\Input\CheckBox::__construct
	 * @group Fieldset
     */
    public function testConstruct()
    {
		$attributes = array('type' => 'checkbox', 'name' => '', 'value' => null);
		
		$instance = new Checkbox();
		
		$this->assertEquals($attributes, $instance->getAttributes());
    }
	
	/**
	 * @covers FuelPHP\Fieldset\Input\Toggle::isChecked
	 * @group Fieldset
	 */
	public function testDefaultChecked()
	{
		$this->assertFalse($this->object->isChecked());
	}
	
	/**
	 * @covers FuelPHP\Fieldset\Input\Toggle::isChecked
	 * @covers FuelPHP\Fieldset\Input\Toggle::setChecked
	 * @group Fieldset
	 */
	public function testGetSetChecked()
	{
		$this->object->setChecked(true);
		
		$this->assertTrue($this->object->isChecked());
	}
	
	/**
	 * @covers FuelPHP\Fieldset\Input\Toggle::setChecked
	 * @expectedException \InvalidArgumentException
	 * @group Fieldset
	 */
	public function testSetNonBool()
	{
		$this->object->setChecked('failure');
	}
}
