<?php

namespace FuelPHP\Fieldset\Input;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-17 at 16:38:28.
 */
class SelectTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
		$this->object = new Select;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
	
	/**
	 * @covers FuelPHP\Fieldset\Input\Select::set
	 * @group Fieldset
     */
    public function testSet()
    {
		$this->object[] = new Select\Option;
		$this->object[] = new Select\Option;
		$this->object[] = new Select\Option;
		$this->object[] = new Select\Option;
		
		$this->assertEquals(4, count($this->object));
    }
	
	/**
	 * @expectedException \InvalidArgumentException
	 * @covers FuelPHP\Fieldset\Input\Select::set
	 * @group Fieldset
	 */
	public function testSetInvalid()
	{
		$this->object[] = '';
	}
	
}
