<?php
namespace FuelPHP\Fieldset\Render;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-17 at 16:38:28.
 */
class BasicRenderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Input
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BasicRender;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

	/**
	 * @covers FuelPHP\Fieldset\Render::renderForm
	 * @covers FuelPHP\Fieldset\Render\BasicRender::input
	 * @covers FuelPHP\Fieldset\Render\BasicRender::form
	 * @group Fieldset
	 */
    public function testRenderForm()
	{
		echo 'asdasd';
		
		$form = new \FuelPHP\Fieldset\Form();
		$form[] = new \FuelPHP\Fieldset\Input();
		$form[] = new \FuelPHP\Fieldset\Input();
		$form[] = new \FuelPHP\Fieldset\Input();
		$form[] = new \FuelPHP\Fieldset\Input('submit', array('type' => 'submit'));
		
		$expected = '<form><input/>
<input/>
<input/>
<input type="submit"/></form>';
		
		$this->assertXmlStringEqualsXmlString(
			$expected,
			$this->object->renderForm($form)
		);
	}
	
	/**
	 * @covers FuelPHP\Fieldset\Render\BasicRender::fieldset
	 * @group Fieldset
	 */
	public function testRenderFieldset()
	{
		$fieldset = new \FuelPHP\Fieldset\Fieldset();
		$fieldset[] = new \FuelPHP\Fieldset\Input();
		$fieldset[] = new \FuelPHP\Fieldset\Input();
		$fieldset[] = new \FuelPHP\Fieldset\Input();
		
		$expected = '<fieldset><input/>
<input/>
<input/></fieldset>';
		
		$this->assertEquals($expected, $this->object->renderFieldset($fieldset));
	}
	
	/**
	 * @covers FuelPHP\Fieldset\Render\BasicRender::fieldset
	 * @group Fieldset
	 */
	public function testRenderFieldsetWithLegend()
	{
		$fieldset = new \FuelPHP\Fieldset\Fieldset();
		$fieldset->setLegend('Test Legend');
		
		$expected = '<fieldset><legend>Test Legend</legend></fieldset>';
		
		$this->assertEquals($expected, $this->object->renderFieldset($fieldset));
	}
	
}
