<?php

namespace FuelPHP\Fieldset\Render;

use FuelPHP\Fieldset\Fieldset;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-20 at 13:34:17.
 */
class RenderTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var Render
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Render;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}

	/**
	 * @group Fieldset
	 * @covers FuelPHP\Fieldset\Render\Render::setFieldset
	 * @covers FuelPHP\Fieldset\Render\Render::getFieldset
	 */
	public function testSetFieldset()
	{
		$this->object->setFieldset($fieldset = new Fieldset);
		$this->assertEquals(
				$fieldset, $this->object->getFieldset()
		);
	}
	
	/**
	 * @group Fieldset
	 * @covers FuelPHP\Fieldset\Render\Render::setInterface
	 * @covers FuelPHP\Fieldset\Render\Render::getInterface
	 */
	public function testSetInterface()
	{
		$this->object->setInterface($interface = new BasicRender);
		$this->assertEquals(
				$interface, $this->object->getInterface()
		);
	}

}
