<?php
namespace Fuel\Fieldset;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-17 at 16:38:28.
 */
class FieldsetTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Fieldset
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Fieldset;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
	
	/**
	 * @covers FuelPHP\Fieldset\Fieldset::setLegend
	 * @covers FuelPHP\Fieldset\Fieldset::getLegend
	 * @group Fieldset
	 */
	public function testSetGetLegend()
	{
		$legend = 'This is a legend';
		
		$this->object->setLegend($legend);
		
		$this->assertEquals(
			$legend,
			$this->object->getlegend()
		);
	}
	
}
