<?php
namespace FuelPHP\Fieldset;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-17 at 16:38:28.
 */
class FormTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Fieldset
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Form;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
	
	/**
	 * @covers FuelPHP\Fieldset\Form::set
	 * @group Fieldset
     */
    public function testArrayAddInput()
    {
		$input = new Input;
		
		$this->object[] = $input;
		
		$this->assertEquals(count($this->object), 1);
    }
	
	/**
	 * @covers FuelPHP\Fieldset\Form::set
	 * @group Fieldset
	 * @expectedException InvalidArgumentException
     */
    public function testArrayAddInvalid()
    {
		$input = 'This should fail';
		
		$this->object[] = $input;
    }
	
}
