<?php
namespace FuelPHP\Fieldset;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-17 at 16:38:28.
 */
class InputTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Input
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Input('');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers FuelPHP\Fieldset\Input::setName
	 * @group Fieldset
     */
    public function testSetName()
    {
		$this->object->setName('test-name');
        $this->assertEquals('test-name', $this->object->getName());
    }

    /**
     * @covers FuelPHP\Fieldset\Input::getName
	 * @group Fieldset
     */
    public function testGetName()
    {
        $this->assertNull($this->object->getName());
    }

    /**
     * @covers FuelPHP\Fieldset\Input::getValue
	 * @group Fieldset
     */
    public function testGetValue()
    {
        $this->assertNull($this->object->getValue());
    }

    /**
     * @covers FuelPHP\Fieldset\Input::setValue
	 * @group Fieldset
     */
    public function testSetValue()
    {
        $this->object->setValue('test-value');
        $this->assertEquals('test-value', $this->object->getValue());
    }
	
	/**
	 * @covers FuelPHP\Fieldset\Input::setName
	 * @expectedException InvalidArgumentException
	 * @group Fieldset
	 */
	public function testInvalidName()
	{
		$this->object->setName(new Input);
	}
	
}
